In [357]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import smote_variants as sv
from imblearn.over_sampling import SMOTE

In [359]:
X_train = np.load('X_train_ffill.npy', allow_pickle=True)
Y_train = np.load('Y_train_ffill.npy', allow_pickle=True)
X_val = np.load('X_val_ffill.npy', allow_pickle=True)
Y_val = np.load('Y_val_ffill.npy', allow_pickle=True)
X_test = np.load('X_test_ffill.npy', allow_pickle=True)
Y_test = np.load('Y_test_ffill.npy', allow_pickle=True)

X_train = np.concatenate((X_train, X_val), axis=0)
Y_train = np.concatenate((Y_train, Y_val), axis=0)

In [361]:
X_train.shape

(337, 11, 30)

In [363]:
Y_train.shape

(337,)

In [365]:

# Verify the shapes
print("Training set shape (X):", X_train.shape)
print("Training set shape (Y):", Y_train.shape)
print("Testing set shape (X):", X_test.shape)
print("Testing set shape (Y):", Y_test.shape)

Training set shape (X): (337, 11, 30)
Training set shape (Y): (337,)
Testing set shape (X): (85, 11, 30)
Testing set shape (Y): (85,)


In [319]:
X_train = np.transpose(X_train, (0, 2, 1))
X_val = np.transpose(X_val, (0, 2, 1))
X_test = np.transpose(X_test, (0, 2, 1))

In [367]:
oversampler= sv.MulticlassOversampling(oversampler='ANS',
                                      oversampler_params={'random_state': 5})

X_train_reshaped = X_train.reshape(X_train.shape[0], -1)
X_train_resampled, Y_train_resampled = smote.fit_resample(X_train_reshaped, Y_train)
X_train_resampled = X_train_resampled.reshape(-1, 11, 30)

In [369]:
X_train_resampled.shape

(490, 11, 30)

In [371]:
Y_train_resampled.shape

(490,)

In [373]:
shuffle_indices = np.random.permutation(np_X_set.shape[0])

# 使用打乱的索引来打乱 array_3d 和 y_set
X_train_resampled = X_train_resampled[shuffle_indices]
Y_train_resampled = Y_train_resampled[shuffle_indices]

In [375]:
from sktime.classification.deep_learning import LSTMFCNClassifier
from sklearn.metrics import accuracy_score
#eucl_dist = FlatDist(ScipyDist())
lstmfcn = LSTMFCNClassifier(n_epochs=20,
                            batch_size=2,
                            dropout=0.8, 
                            kernel_sizes=(3, 3, 3), 
                            filter_sizes=(64, 64, 64), 
                            lstm_size=8)  
lstmfcn.fit(X_train_resampled, Y_train_resampled)
Y_pred = lstmfcn.predict(X_test)
accuracy_score(Y_test, Y_pred)

43/43 [==============================] - 1s 3ms/step


0.8823529411764706

In [376]:
Y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [377]:
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
KNN = KNeighborsTimeSeriesClassifier(distance="euclidean")
KNN.fit(X_train_resampled, Y_train_resampled)
Y_pred = KNN.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.8588235294117647

In [378]:
Y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])

In [379]:
from sktime.classification.deep_learning.mlp import MLPClassifier
mlp = MLPClassifier(n_epochs=5,batch_size=1)  
mlp.fit(X_train_resampled, Y_train_resampled)  
Y_pred = mlp.predict(X_test)
accuracy_score(Y_test, Y_pred)

85/85 [==============================] - 0s 2ms/step


0.7647058823529411

In [380]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [381]:
from sktime.classification.deep_learning.cnn import CNNClassifier
cnn = CNNClassifier(n_epochs=5,batch_size=1)  
cnn.fit(X_train_resampled, Y_train_resampled)   
Y_pred = cnn.predict(X_test)
accuracy_score(Y_test, Y_pred)

85/85 [==============================] - 0s 2ms/step


0.8705882352941177

In [382]:
Y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [383]:
from sktime.classification.deep_learning.fcn import FCNClassifier
FCN = FCNClassifier(n_epochs=10,batch_size=1)  
FCN.fit(X_train_resampled, Y_train_resampled)  
Y_pred = FCN.predict(X_test)
accuracy_score(Y_test, Y_pred)

85/85 [==============================] - 0s 2ms/step


0.7058823529411765

In [384]:
Y_pred

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [385]:
from sktime.classification.deep_learning.cntc import CNTCClassifier
CNTCC = FCNClassifier(n_epochs=10,batch_size=1)  
CNTCC.fit(X_train_resampled, Y_train_resampled)  
Y_pred = CNTCC.predict(X_test)
accuracy_score(Y_test, Y_pred)

85/85 [==============================] - 0s 2ms/step


0.7647058823529411

In [386]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [387]:
from sktime.classification.deep_learning import InceptionTimeClassifier
Inception = InceptionTimeClassifier(n_epochs=10,batch_size=2)  
Inception.fit(X_train_resampled, Y_train_resampled)  
Y_pred = Inception.predict(X_test)
accuracy_score(Y_test, Y_pred)

43/43 [==============================] - 1s 4ms/step


0.788235294117647

In [388]:
Y_pred

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1])